src/Entity/Car.php
<?php

namespace App\Entity;

use App\Repository\CarRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CarRepository::class)
 */
class Car
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=100)
     */
    private $brand;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $model;

    /**
     * @ORM\Column(type="integer")
     */
    private $year;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $fuel;

    /**
     * @ORM\Column(type="string", length=30)
     */
    private $gear;

    /**
     * @ORM\Column(type="boolean")
     */
    private $airbag;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $luggage_volume;

    /**
     * @ORM\Column(type="integer", nullable=true)
     */
    private $seats;

    /**
     * @ORM\Column(type="boolean")
     */
    private $air_conditioning;

    /**
     * @ORM\Column(type="integer")
     */
    private $min_license_year;

    /**
     * @ORM\Column(type="integer")
     */
    private $min_driver_age;

    /**
     * @ORM\Column(type="integer")
     */
    private $km;

    /**
     * @ORM\Column(type="integer")
     */
    private $daily_price;

    /**
     * @ORM\Column(type="integer")
     */
    private $daily_max_km;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     */
    private $img_src;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $img_alt;

    /**
     * @ORM\Column(type="string", nullable=true, length=40)
     */
    private $class;

    /**
     * @ORM\ManyToOne(targetEntity=Company::class, inversedBy="cars")
     * @ORM\JoinColumn(nullable=false)
     */
    private $owner_id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $created_at;

    /**
     * @ORM\OneToMany(targetEntity=Transaction::class, mappedBy="car_id")
     */
    private $transactions;

    /**
     * @ORM\Column(type="boolean")
     */
    private $available;

    public function __construct()
    {
        $this->transactions = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getBrand(): ?string
    {
        return $this->brand;
    }

    public function setBrand(string $brand): self
    {
        $this->brand = $brand;

        return $this;
    }

    public function getModel(): ?string
    {
        return $this->model;
    }

    public function setModel(string $model): self
    {
        $this->model = $model;

        return $this;
    }

    public function getYear(): ?int
    {
        return $this->year;
    }

    public function setYear(int $year): self
    {
        $this->year = $year;

        return $this;
    }

    public function getFuel(): ?string
    {
        return $this->fuel;
    }

    public function setFuel(string $fuel): self
    {
        $this->fuel = $fuel;

        return $this;
    }

    public function getGear(): ?string
    {
        return $this->gear;
    }

    public function setGear(string $gear): self
    {
        $this->gear = $gear;

        return $this;
    }

    public function getAirbag(): ?bool
    {
        return $this->airbag;
    }

    public function setAirbag(bool $airbag): self
    {
        $this->airbag = $airbag;

        return $this;
    }

    public function getLuggageVolume(): ?int
    {
        return $this->luggage_volume;
    }

    public function setLuggageVolume(?int $luggage_volume): self
    {
        $this->luggage_volume = $luggage_volume;

        return $this;
    }

    public function getSeats(): ?int
    {
        return $this->seats;
    }

    public function setSeats(?int $seats): self
    {
        $this->seats = $seats;

        return $this;
    }

    public function getAirConditioning(): ?bool
    {
        return $this->air_conditioning;
    }

    public function setAirConditioning(bool $air_conditioning): self
    {
        $this->air_conditioning = $air_conditioning;

        return $this;
    }

    public function getMinLicenseYear(): ?int
    {
        return $this->min_license_year;
    }

    public function setMinLicenseYear(int $min_license_year): self
    {
        $this->min_license_year = $min_license_year;

        return $this;
    }

    public function getMinDriverAge(): ?int
    {
        return $this->min_driver_age;
    }

    public function setMinDriverAge(int $min_driver_age): self
    {
        $this->min_driver_age = $min_driver_age;

        return $this;
    }

    public function getKm(): ?int
    {
        return $this->km;
    }

    public function setKm(int $km): self
    {
        $this->km = $km;

        return $this;
    }

    public function getDailyPrice(): ?int
    {
        return $this->daily_price;
    }

    public function setDailyPrice(int $daily_price): self
    {
        $this->daily_price = $daily_price;

        return $this;
    }

    public function getDailyMaxKm(): ?int
    {
        return $this->daily_max_km;
    }

    public function setDailyMaxKm(int $daily_max_km): self
    {
        $this->daily_max_km = $daily_max_km;

        return $this;
    }

    public function getImgSrc(): ?string
    {
        return $this->img_src;
    }

    public function setImgSrc(?string $img_src): self
    {
        $this->img_src = $img_src;

        return $this;
    }

    public function getImgAlt(): ?string
    {
        return $this->img_alt;
    }

    public function setImgAlt(string $img_alt): self
    {
        $this->img_alt = $img_alt;

        return $this;
    }

    public function getClass(): ?string
    {
        return $this->class;
    }

    public function setClass(?string $class): self
    {
        $this->class = $class;

        return $this;
    }

    public function getOwnerId(): ?Company
    {
        return $this->owner_id;
    }

    public function setOwnerId(?Company $owner_id): self
    {
        $this->owner_id = $owner_id;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeInterface $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }

    /**
     * @return Collection|Transaction[]
     */
    public function getTransactions(): Collection
    {
        return $this->transactions;
    }

    public function addTransaction(Transaction $transaction): self
    {
        if (!$this->transactions->contains($transaction)) {
            $this->transactions[] = $transaction;
            $transaction->setCarId($this);
        }

        return $this;
    }

    public function removeTransaction(Transaction $transaction): self
    {
        if ($this->transactions->removeElement($transaction)) {
            // set the owning side to null (unless already changed)
            if ($transaction->getCarId() === $this) {
                $transaction->setCarId(null);
            }
        }

        return $this;
    }

    public function getAvailable(): ?bool
    {
        return $this->available;
    }

    public function setAvailable(bool $available): self
    {
        $this->available = $available;

        return $this;
    }

    public function __toString()
    {
        return $this->getBrand().' '.$this->getModel().' '.$this->getYear();
    }
}

src/Controller/HomeController.php
<?php

namespace App\Controller;

use App\Entity\Transaction;
use App\Form\ReservationType;
use App\Repository\CarRepository;
use App\Service\TransactionService;
use DateTime;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Component\Form\FormFactoryInterface;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\HttpFoundation\Session\Flash\FlashBagInterface;
use Symfony\Component\Routing\Annotation\Route;
use Symfony\Component\Routing\RouterInterface;
use Symfony\Component\Security\Core\Security;
use Symfony\Component\Validator\Constraints\Date;
use Twig\Environment;

class HomeController
{
    private $twig;
    private $router;
    private $flash;

    public function __construct(Environment $twig, RouterInterface $router, FlashBagInterface $flash)
    {
        $this->twig = $twig;
        $this->router = $router;
        $this->flash = $flash;
    }

    /**
     * @Route("/", name="home")
     * @param CarRepository $carRepository
     * @return Response
     */
    public function index(CarRepository $carRepository): Response
    {
        $cars = $carRepository->findBy(['available' => 1], ['daily_price' => 'DESC' ]);

        $content = $this->twig->render('home/index.html.twig', [
            'cars' => $cars
        ]);

        return new Response($content);
    }

    /**
     * @Route("/rent/{id}", name="rent")
     * @param FormFactoryInterface $formFactory
     * @param Request $request
     * @param EntityManagerInterface $em
     * @param TransactionService $service
     * @param Security $security
     * @param CarRepository $carRepo
     * @param null $id
     * @return Response
     */
    public function rent(
        FormFactoryInterface $formFactory,
        Request $request,
        EntityManagerInterface $em,
        TransactionService $service,
        Security $security,
        CarRepository $carRepo,
        $id = null
    ): Response
    {
        if($security->isGranted('ROLE_USER')){
            $car = $carRepo->find($id);

            $transaction = new Transaction();

            $form = $formFactory->create(ReservationType::class, $transaction);
            $form->handleRequest($request);

            if ($form->isSubmitted() && $form->isValid()) {
                $date = $form->get('date')->getData();
                $date = $service->parseDate($date);

                $start = strtotime($date[0]);
                $end = strtotime("now");

                if($start < $end){
                    $this->flash->add('warning', 'Reservation date must be bigger than today.');
                }else {
                    $transaction->setPickupDate(new DateTime($date[0]));
                    $transaction->setReturnDate(new DateTime($date[1]));

                    $days = $service->dateDiff($date[0], $date[1]);
                    $daily_price = $car->getDailyPrice();
                    $daily_km = $car->getDailyMaxKm();

                    $transaction->setPickupCarKm($car->getKm());
                    $transaction->setAmount($service->calculateAmount($daily_price, $days));
                    $transaction->setReturnCarKm($service->calculateExpectedCarKM($daily_km, $days));

                    $transaction->setCarId($car);

                    $transaction->setCustomerId($security->getUser());
                    $transaction->setStatus(1);
                    $car->setAvailable(0);

                    $transaction->setDate(new DateTime());
                    $this->flash->add('success', 'Reservation was successful.');

                    $em->persist($transaction);
                    $em->flush();
                }

                return new RedirectResponse($this->router->generate('home'));
            }

            $content = $this->twig->render('home/rent.html.twig', [
                'form' => $form->createView(),
                'car' => $car
            ]);

            return new Response($content);
        }else {
            return new RedirectResponse($this->router->generate('app_login'));
        }

    }

}

templates/home/index.html.twig
{% extends 'base.html.twig' %}

{% set route = app.request.attributes.get('_route') %}
{% set parent_route = route|split('_') %}

{% block title %}Rentcar Homepage!{% endblock %}

{% block body %}
<main>
    <div class="album py-5 bg-light">
        <div class="container">
            {% for label, messages in app.flashes %}
                {% for message in messages %}
                    <div class="alert alert-{{label}} alert-dismissible fade show" role="alert">
                        <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        {{message}}
                    </div>
                {% endfor %}
            {% endfor %}
            <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3">
                {% for car in cars %}
                    <div class="col">
                        <div class="card shadow-sm">
                            {% set image = 'uploads/images/' ~ car.imgSrc %}
                            <img src="{{ asset(image) }}" alt="{{ car.imgAlt }}" />
                            <div class="card-body">
                                <p class="card-text">{{ car.year }} {{ car.brand }} {{ car.model }}
                                    <span class="text-muted">
                                        {{ car.class }}
                                    </span>
                                </p>
                                <ul class="list-group mb-2">
                                    <li class="list-group-item">
                                        <div class="col-md-12 row text-center">
                                            <div class="col-md-auto">
                                                <small class="text-muted">
                                                    <i class="fas fa-gas-pump"></i> {{ car.fuel }}
                                                </small>
                                            </div>
                                            <div class="col-md-6">
                                                <small class="text-muted">
                                                    <i class="fas fa-cog"></i> {{ car.gear }}
                                                </small>
                                            </div>
                                            <div class="col-md-auto">
                                                <small class="text-muted">
                                                    {{ car.dailyPrice }} ₺
                                                </small>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="list-group-item">
                                        <div class="col-md-12 row text-center">
                                            <div class="col-md-3">
                                                <small class="text-muted">
                                                    {% if car.airConditioning == 1 %}
                                                        <i class="fas fa-cloud"></i>
                                                    {% endif %}
                                                </small>
                                            </div>
                                            <div class="col-md-3">
                                                <small class="text-muted">
                                                    {% if car.airbag == 1 %}
                                                        <i class="fas fa-fan"></i>
                                                    {% endif %}
                                                </small>
                                            </div>
                                            <div class="col-md-3">
                                                <small class="text-muted">
                                                    <i class="fas fa-car"></i> {{ car.seats }}
                                                </small>
                                            </div>
                                            <div class="col-md-3">
                                                <small class="text-muted">
                                                    {% if car.luggageVolume %}
                                                        <i class="fas fa-luggage-cart"></i> {{ car.luggageVolume }}
                                                    {% endif %}
                                                </small>
                                            </div>
                                        </div>
                                    </li>
                                    <li class="list-group-item">
                                        <small class="text-muted">
                                            Daily Max. KM {{ car.dailyMaxKm }}
                                        </small>
                                    </li>
                                    <li class="list-group-item">
                                        <small class="text-muted">
                                            Min. {{ car.minDriverAge }} age
                                        </small>
                                    </li>
                                    <li class="list-group-item">
                                        <small class="text-muted">
                                            Min. {{ car.minLicenseYear }} Years of Driver's License
                                        </small>
                                    </li>
                                </ul>
                                <div class="d-flex justify-content-end align-items-center">
                                    <div class="btn-group">
                                        <a href="{{ path('rent', {id: car.id}) }}" class="btn btn-sm btn-outline-secondary">
                                            Rent
                                            <i class="fas fa-chevron-right"></i>
                                        </a>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>
</main>
{% endblock %}

templates/home/rent.html.twig
{% extends 'base.html.twig' %}

{% set route = app.request.attributes.get('_route') %}
{% set parent_route = route|split('_') %}

{% block title %}Rentcar Homepage!{% endblock %}

{% block stylesheets %}
    <link rel="stylesheet" type="text/css" href="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.css" />
{% endblock %}

{% block body %}
    <main class="bg-light">
        <div class="container pt-5 pb-5">
            <h3 class="fs-2 text pb-2">Reservation a Car</h3>

            <div class="col">
                <div class="card shadow-sm">
                    {% set image = 'uploads/images/' ~ car.imgSrc %}
                    <img src="{{ asset(image) }}" alt="{{ car.imgAlt }}" class="col-md-6"/>
                    <div class="card-body">
                        <p class="card-text">{{ car.year }} {{ car.brand }} {{ car.model }}
                            <span class="text-muted">
                                {{ car.class }}
                            </span>
                        </p>
                        <ul class="list-group mb-2">
                            <li class="list-group-item">
                                <div class="col-md-12 row text-center">
                                    <div class="col-md-auto">
                                        <small class="text-muted">
                                            <i class="fas fa-gas-pump"></i> {{ car.fuel }}
                                        </small>
                                    </div>
                                    <div class="col-md-6">
                                        <small class="text-muted">
                                            <i class="fas fa-cog"></i> {{ car.gear }}
                                        </small>
                                    </div>
                                    <div class="col-md-auto">
                                        <small class="text-muted">
                                            {{ car.dailyPrice }} ₺
                                        </small>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <div class="col-md-12 row text-center">
                                    <div class="col-md-3">
                                        <small class="text-muted">
                                            {% if car.airConditioning == 1 %}
                                                <i class="fas fa-cloud"></i>
                                            {% endif %}
                                        </small>
                                    </div>
                                    <div class="col-md-3">
                                        <small class="text-muted">
                                            {% if car.airbag == 1 %}
                                                <i class="fas fa-fan"></i>
                                            {% endif %}
                                        </small>
                                    </div>
                                    <div class="col-md-3">
                                        <small class="text-muted">
                                            <i class="fas fa-car"></i> {{ car.seats }}
                                        </small>
                                    </div>
                                    <div class="col-md-3">
                                        <small class="text-muted">
                                            {% if car.luggageVolume %}
                                                <i class="fas fa-luggage-cart"></i> {{ car.luggageVolume }}
                                            {% endif %}
                                        </small>
                                    </div>
                                </div>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">
                                    Daily Max. KM {{ car.dailyMaxKm }}
                                </small>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">
                                    Min. {{ car.minDriverAge }} age
                                </small>
                            </li>
                            <li class="list-group-item">
                                <small class="text-muted">
                                    Min. {{ car.minLicenseYear }} Years of Driver's License
                                </small>
                            </li>
                        </ul>
                        {{ form_start(form) }}

                        <div class="d-flex justify-content-between align-items-center">
                            {{ form_widget(form.date, {'attr': {'id': 'date', 'class': 'col-md-8'}}) }}
                            <div class="btn-group">
                                {{ form_widget(form.save, {'attr': {'class': 'btn btn-primary float-right'}}) }}
                            </div>
                        </div>
                        {{ form_end(form) }}
                    </div>
                </div>
            </div>
        </div>
    </main>
{% endblock %}

{% block javascripts %}
    <script type="text/javascript" src="https://cdn.jsdelivr.net/jquery/latest/jquery.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/momentjs/latest/moment.min.js"></script>
    <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/daterangepicker/daterangepicker.min.js"></script>

    <script>
        $(function() {
            $('#reservation_date').daterangepicker({
                timePicker: true,
                startDate: moment().startOf('hour'),
                endDate: moment().startOf('hour').add(32, 'hour'),
                locale: {
                    format: 'MM/DD/YYYY HH:mm'
                }
            });
        });
    </script>

{% endblock %}